## load packages
library(dplyr)
library(purrr)
library(ggplot2)

## set working directory to the location of the master "word_embeddings" folder
setwd("")

## functions
source('./code/functions.R')

## get file names of mturk output data
all_files <- as.list(list.files('./data/mturk/triad_task/output/'))  # list all files in folder
survey_files <- all_files[grepl("survey", all_files)]  # identify files with survey responses
triad_task_files <- all_files[grepl("tt", all_files)]  # identify files with triad-task choices
rm(all_files) # rm unnecessary files from Data environment

## load nearest neighbors data
# these are the top 10 nearest neighbors for each of the 10 cues generated by the pretrained models we evaluated
nn_list <- readRDS("./data/mturk/triad_task/input_data/nn_list.rds")

## load and process mturk triad task responses
tt_tibble <- lapply(paste0('./data/mturk/triad_task/output/', triad_task_files), loadTT) # function loads and cleans triad task responses
tt_tibble <- do.call(rbind, tt_tibble) # bind output into a single tibble
cues <- unique(tt_tibble$cue)
rm(triad_task_files, loadTT)

## load and process mturk survey responses
survey_tibble <- paste0('./data/mturk/triad_task/output/', survey_files) %>% map(read.table, sep = ",", header = TRUE, stringsAsFactors = FALSE)
survey_tibble <- do.call(rbind, survey_tibble) # bind output into a single tibble
rm(survey_files)

## select models to be compared (models[2] is the basline)
models = c('glove', 'w2v')

## conmpute probability of the same token being selected from both models
overlap_probabilities <- lapply(cues, function(x) compute_overlap_prob(nns1 = nn_list[[models[1]]][[x]], nns2 = nn_list[[models[2]]][[x]])) %>% unlist() %>% setNames(cues)

# bootstrap relative performance metric
plot_tibble <- lapply(cues, function(x) bootstrap_relative_performance(tt_tibble, x, models, overlap_prob = overlap_probabilities[[x]], num_iters = 100, seed = 1984L))
plot_tibble <- do.call(rbind, plot_tibble) %>% arrange(-mu) %>% mutate(cue = factor(cue, levels = cue))

# plot
ggplot(plot_tibble, aes(x = cue, y = mu)) +
  geom_bar(position = position_dodge(), stat = "identity", fill = "gray70") + 
  geom_hline(yintercept = 1, colour="black", linetype="dashed") +
  geom_errorbar(aes(ymin = mu - 1.96*std.error, ymax = mu + 1.96*std.error), width = 0.2, position = position_dodge(0.9), size = 0.75) +
  xlab("") + ylab("Relative Performance") +
  ylim(0, 2) +
  theme(plot.title = element_text(size=20, margin = margin(t = 20, r = 0, b = 0, l = 0)), panel.background = element_blank(),
        axis.text.x = element_text(size=18, angle = 90, margin = margin(t = -10, r = 0, b = 0, l = 0)),
        axis.text.y = element_text(size=18),
        axis.ticks.x=element_blank(),
        axis.title.y = element_text(size=20, margin = margin(t = 0, r = 15, b = 0, l = 15)),
        axis.title.x = element_text(size=20, margin = margin(t = 15, r = 0, b = 15, l = 0)))
ggsave(paste0('./figures/fg25_app.eps'), dpi = 800)





